# Generated by Django 6.0.1 on 2026-02-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
            options={
                'verbose_name_plural': 'ProductCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Coragen 60ml', max_length=200)),
                ('product_type', models.CharField(choices=[('seed', 'Seeds'), ('pesticide', 'Pesticide/Insecticide'), ('fertilizer', 'Fertilizer')], max_length=20)),
                ('technical_name', models.CharField(blank=True, max_length=255)),
                ('target_crops', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('weight_volume', models.DecimalField(decimal_places=2, help_text='e.g., 100', max_digits=10)),
                ('unit', models.CharField(choices=[('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('pkty', 'Packet')], help_text='e.g., ml', max_length=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
