# Generated by Django 6.0.1 on 2026-02-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productcategory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
