# Generated by Django 6.0.1 on 2026-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='toxicity_levels',
            field=models.CharField(choices=[('red', 'Red (Extremely Toxic)'), ('yellow', 'Yellow (Highly Toxic)'), ('blue', 'Blue (Moderately Toxic)'), ('green', 'Green (Slightly Toxic)'), ('None', 'No Toxicity/Organic')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
