# Generated by Django 6.0.1 on 2026-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('seed', 'Seeds'), ('pesticide', 'Pesticide/Insecticide'), ('fertilizer', 'Fertilizer'), ('tools', 'Tools')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('pkty', 'Packet'), ('unit', 'Unit')], help_text='e.g., ml', max_length=10),
        ),
    ]
